from clarifai.rest import ClarifaiApp


def get_tags_from_image(image_url):
    # api key generated by me
    app = ClarifaiApp(api_key='c4b15eb42c0f422aa9ac0bfd19a0b104')
    # get the general model
    model = app.models.get("general-v1.3")
    # predict with the model
    r = model.predict_by_url(url= image_url)
    return r
