# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_verified_mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='Ananymous', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='ananymous', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='ananymous', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Ananymous', max_length=120),
        ),
    ]
