# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvote_number',
            field=models.IntegerField(default=0),
        ),
    ]
