# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_comment_upvote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessiontoken',
            name='last_request_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
